import mlflow.store.model_registry.sqlalchemy_store as registry_store
import mlflow.store.tracking.sqlalchemy_store as tracking_store
from mlflow_custom_ext.notifying_store import NotifyingRegistryStore, NotifyingTrackingStore

registry_store.SqlAlchemyStore = NotifyingRegistryStore
tracking_store.SqlAlchemyStore = NotifyingTrackingStore